

export const GET_CHICKEN_REQUEST = 'GET_CHICKEN_REQUEST'
export const GET_CHICKEN_SUCCESS = 'GET_CHICKEN_SUCCESS'
export const GET_CHICKEN_FAILURE = 'GET_CHICKEN_FAILURE'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAILURE = 'GET_CART_FAILURE'

//on cart page for quantity
export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';


export const GET_SEAFOOD_REQUEST = 'GET_SEAFOOD_REQUEST'
export const GET_SEAFOOD_SUCCESS = 'GET_SEAFOOD_SUCCESS'
export const GET_SEAFOOD_FAILURE = 'GET_SEAFOOD_FAILURE'

export const SUB_PRODUCTS_QUANTITY = "SUB_PRODUCTS_QUANTITY";
export const ADD_PRODUCTS_QUANTITY = "ADD_PRODUCTS_QUANTITY";