

export const GET_CHICKEN_REQUEST = 'GET_CHICKEN_REQUEST'
export const GET_CHICKEN_SUCCESS = 'GET_CHICKEN_SUCCESS'
export const GET_CHICKEN_FAILURE = 'GET_CHICKEN_FAILURE'



export const GET_SEAFOOD_REQUEST = 'GET_SEAFOOD_REQUEST'
export const GET_SEAFOOD_SUCCESS = 'GET_SEAFOOD_SUCCESS'
export const GET_SEAFOOD_FAILURE = 'GET_SEAFOOD_FAILURE'

export const SUB_PRODUCTS_QUANTITY = "SUB_PRODUCTS_QUANTITY";
export const ADD_PRODUCTS_QUANTITY = "ADD_PRODUCTS_QUANTITY";